services:

    mariadb:
      image: mariadb:user
      container_name: mariadb
      build: ./requirements/mariadb/
      env_file:
        - .env
      volumes:
        - mariadb:/var/lib/mysql
      expose: 
        - "3306"
      networks:
        - inception
      restart: always
      healthcheck:
        test: ["CMD", "sh", "-c", "mysqladmin ping -h localhost -u root -p$SQL_ROOT_PWD"]
        interval: 30s
        timeout: 20s
        retries: 5
        start_period: 60s

    redis:
      image: redis:user
      container_name: redis
      build: ./requirements/bonus/redis/
      expose:
        - "6379"
      networks:
        - inception
      restart: always
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 30s
        timeout: 10s
        retries: 3

    nginx:
      image: nginx:user
      container_name: nginx
      build: ./requirements/nginx/
      ports:
        - "443:443"
      env_file:
        - .env
      depends_on:
        - wordpress
        - static-site
      volumes:
        - wordpress:/var/www/wordpress
        - static-site:/var/www/static
      networks:
        - inception
      restart: always

    wordpress:
      image: wordpress:user
      container_name: wordpress
      build: ./requirements/wordpress/
      env_file:
        - .env
      volumes:
        - wordpress:/var/www/wordpress
      expose:
        - "9000"
      depends_on:
        mariadb:
          condition: service_healthy
        redis:
          condition: service_healthy
      networks:
        - inception
      restart: always

    ftp:
      image: ftp:user
      container_name: ftp
      build: ./requirements/bonus/ftp/
      env_file:
        - .env
      ports:
        - "21:21"
        - "21000-21010:21000-21010"
      volumes:
        - wordpress:/var/ftp/wordpress
      networks:
        - inception
      restart: always

    static-site:
      image: static-site:user
      container_name: static-site
      build: ./requirements/bonus/static-site/
      expose:
        - "80"
      networks:
        - inception
      restart: always

    adminer:
      image: adminer:user
      container_name: adminer
      build: ./requirements/bonus/adminer
      depends_on:
        - mariadb
      ports:
        - "8080:8080"
      networks:
        - inception
      restart: always
    
    portainer:
      image: portainer/portainer-ce:2.11.1
      container_name: portainer
      restart: always
      ports:
        - "8000:8000"
        - "9443:9443"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
      networks:
        - inception
        
networks:
  inception:
    name: inception

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/fcrocq/data/mariadb
      o: bind
      type: none

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/fcrocq/data/wordpress
      o: bind
      type: none
  
  static-site:
    name: static-site
    driver: local
    driver_opts:
      device: /home/fcrocq/data/static-site
      o: bind
      type: none
    
  portainer_data:
